### PR TITLE
category schema added

### LINKED ISSUE #36: Create Category DB Model

### PR DESCRIPTION
**Pull request by devalparikh**

### CODE REVIEW

**Comment by jeromesteve202** [comment]
Should we also consider adding an image attribute to the schema?

**Comment by devalparikh** [comment]
> Should we also consider adding an image attribute to the schema?

YES good idea definitely something to consider adding even though it isn't in our initial design

**Review by alexandrofuentelzas — APPROVED** [review]
follows the user.ts. looks good

**Review by jeromesteve202 — APPROVED** [review]
nice work, straightforward and has everything we need as designed on confluence.

**Pull request merged**
